### ISSUE TITLE
Spec Version

### ISSUE THREAD

**Issue by rizo** [edma2/clojure-msgpack#2]
Hi,
Could you provide some information about the version of the spec that's implemented? I'm trying to unpack some test data, previously packed from Clojure, in, e.g., Python, and the result I get is just a literal `0`.

Here's the example of the output (assuming the data is stored in a redis db):

![screen shot 2015-01-19 at 15 48 27](https://cloud.githubusercontent.com/assets/308413/5803075/ec8c90f0-9ff2-11e4-9351-b99b6c811e36.png)

**Comment by edma2** [comment]
It's unclear to me how you got those bytes. How do I reproduce that?

```clojure
user=> (with-open [os (output-stream "/tmp/test.bin")]
	(let [data (pack {:compact true :schema 0})]
			 (.write os data 0 (count data))))
  #_=>   #_=> nil
```
```sh
% hexdump /tmp/test.bin
0000000 82 a6 73 63 68 65 6d 61 00 a7 63 6f 6d 70 61 63
0000010 74 c3                                          
0000012
```
