### ISSUE TITLE
not all releases support str8, so there are compatibility issues.

### ISSUE THREAD

**Issue by ginahagg** [edma2/clojure-msgpack#24]
Could you please add a compatibility switch to force clojure-msgpack to create str16 serializations instead of str8.

**Comment by edma2** [comment]
@ginahagg yes, I'll add a compatibility mode flag

**Comment by ginahagg** [comment]
Thank you :)

**Comment by edma2** [comment]
Just published version 1.2.0 which adds the `:compatibility-mode` flag (see README.md). Apologies for the delay.

**Comment by ginahagg** [comment]
Thank you so much :) Much appreciated.

**Comment by edma2** [comment]
You're welcome, thanks for the report!
