### ISSUE TITLE
Can't use with lein try

### ISSUE THREAD

**Issue by bass3m** [edma2/clojure-msgpack#3]
Perhaps it's an issue with how this library is referenced in clojars, but i'm unable to use this with lein try.
I tried : lein try clojure-msgpack , lein try edma2/clojure-msgpack, lein try clojure-msgpack/clojure-msgpack and they all fail.
In the meantime other libraries work, for example: lein try reiddraper/simple-check or lein try clj-msgpack.
Update: i'm not sure if it's related to sonatype ? [sonatype_ops tweet](https://twitter.com/sonatype_ops/status/561195117952765954)

**Comment by edma2** [comment]
You have to pass the version to lein try because I don't have a "RELEASE" version (I should probably fix this).
$ lein try clojure-msgpack 0.1.0-SNAPSHOT
