### ISSUE TITLE
Remove snapshot designation

### ISSUE THREAD

**Issue by jmelching** [edma2/clojure-msgpack#5]
Its generally bad practice to include snapshot versions in releases.  Any thoughts on removing the snapshot version and releasing a 0.1.0 version?  

Also, I'd like to get your latest changes for reflection removal, any idea when it might be pushed to clojars?

**Comment by edma2** [comment]
Just did a big rewrite. I'll get a stable version up ASAP.

**Comment by edma2** [comment]
Stable version (1.0.0) is on clojars!
