### ISSUE TITLE
Why does msgpack.core/pack return a Seq?

### ISSUE THREAD

**Issue by tyano** [edma2/clojure-msgpack#8]
In my opition, the main purpose of msgpack library is converting an object to msgpack-formatted byte-array or a byte-array to an object.

But msgpack.core/pack returns (seq (.toByteArray output-stream)). Why do you need use 'seq' here? 
In older version of clojure-msgpack simplly returned a msgpack-formatted byte-array.

In 1.0.0, I need to convert the seq into a byte-array again before sending it into network...

**Comment by edma2** [comment]
My original intention was to return something more clojure-like and immutable. The obvious data-type that fits this criteria is a seq, but you don't get any of the benefits of laziness. I should just return the byte array to avoid the extra seq allocations.

By the way, if you plan on sending this over the network directly, are you able to use the streaming interface? It's more efficient.

Thanks for the feedback!

**Comment by tyano** [comment]
Hi, sorry for my late response. I think this issue is worth for a discussion, so I want continue...

First, I think returning a byte-array as a result of 'pack' is better. it is the most performative and no disadvantage as a clojure data (see next paragraph).

Second, I think it is not important a return value is a 'clojure-like' object (in this case, a seq), but the important point is that the return value is 'seqable' (object that be able to 'seq'), because most of clojure functions like filter, map or doseq etc automatically convert every passed parameter into a seq if it is seqable. So we don't need to care about the real-type of parameters before calling a clojure function. I think it is a clojure-way.  
So it the return value of 'pack' is a byte-array, it will be treated a seq automatically.

At last, I want to explain about my usecase.

I'm using clojure-msgpack with Aleph (high performance TCP/HTTP server of clojure based on Netty. https://github.com/ztellman/aleph). Aleph (and Netty) is a Message-oriented (not stream-oriented), so every message is an object, and then converted into a byte-array and then pushed into a Channel. There is no OutputStream. So I don't use pack-stream, but use pack for converting an object into byte-array. 

I think Aleph is a most famous TCP server of clojure, and message-pack is a library for TCP communications, so it is better that clojure-msgpack is easily applicable to Aleph (Netty). If the return value of 'pack' is an byte-array, clojure-msgpack will be more easily applicable.

Thank you.

**Comment by edma2** [comment]
Thanks for the explanation. I understand your use case and agree it should just be a byte array.
This is fixed in 180c338fdcba3bca.
